<?php

$contents = file( "output.txt" );

for( $i=0; $i<count($contents); $i++ ){
	$contents[$i] = ereg_replace( " 1 ", " 01 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 2 ", " 02 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 3 ", " 03 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 4 ", " 04 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 5 ", " 05 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 6 ", " 06 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 7 ", " 07 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 8 ", " 08 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 9 ", " 09 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 0 ", " 00 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 1 ", " 01 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 2 ", " 02 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 3 ", " 03 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 4 ", " 04 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 5 ", " 05 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 6 ", " 06 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 7 ", " 07 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 8 ", " 08 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 9 ", " 09 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 0 ", " 00 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 1 ", " 01 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 2 ", " 02 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 3 ", " 03 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 4 ", " 04 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 5 ", " 05 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 6 ", " 06 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 7 ", " 07 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 8 ", " 08 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 9 ", " 09 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 0 ", " 00 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 1 ", " 01 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 2 ", " 02 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 3 ", " 03 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 4 ", " 04 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 5 ", " 05 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 6 ", " 06 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 7 ", " 07 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 8 ", " 08 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 9 ", " 09 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 0 ", " 00 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 1 ", " 01 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 2 ", " 02 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 3 ", " 03 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 4 ", " 04 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 5 ", " 05 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 6 ", " 06 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 7 ", " 07 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 8 ", " 08 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 9 ", " 09 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 0 ", " 00 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 1 ", " 01 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 2 ", " 02 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 3 ", " 03 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 4 ", " 04 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 5 ", " 05 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 6 ", " 06 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 7 ", " 07 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 8 ", " 08 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 9 ", " 09 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 0 ", " 00 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 1 ", " 01 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 2 ", " 02 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 3 ", " 03 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 4 ", " 04 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 5 ", " 05 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 6 ", " 06 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 7 ", " 07 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 8 ", " 08 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 9 ", " 09 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 0 ", " 00 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 1 ", " 01 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 2 ", " 02 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 3 ", " 03 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 4 ", " 04 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 5 ", " 05 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 6 ", " 06 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 7 ", " 07 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 8 ", " 08 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 9 ", " 09 ", $contents[$i] );
	$contents[$i] = ereg_replace( " 0 ", " 00 ", $contents[$i] );

	$contents[$i] = ereg_replace( " ", "", $contents[$i] );
echo $contents[$i];
}



?>